spring:
  profiles:
    active: env

  datasource:
    druid:
      initial-size: 3
      max-wait: 6000
      max-active: 20
      min-idle: 1
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      filters: stat,wall
      aop-patterns: javax.sql.*

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.map,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 1000
        profile-enable: true

      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
