spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bishe?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: lala
    password: lalalalala
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    password: lalalalala
    database: 1